program: run_foil_sequence.py
method: grid
metric:
  goal: maximize
  name: "effective_avg"
parameters:
  theta:
    values:
      - 5
      - 10
      - 15
      - 20
      - 25
      - 30
      - 35
      - 40
      - 45
      - 50
      - 55
      - 60
      - 65
      - 70
    distribution: categorical
  AD:
    values:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      - 0.6
      - 0.7
      - 0.8
      - 0.9
      - 1
    distribution: categorical
  Phi:
    values:
      - 180
      - 190
      - 200
      - 210
      - 220
      - 230
      - 240
      - 250
      - 260
      - 270
      - 280
      - 290
      - 300
    distribution: categorical
  St:
    values:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.15
      - 0.25
      - 0.35
    distribution: categorical

