algo: rsac
envparameters:
  action_continuous: true
  action_space: 1
  n_player: 1
  obs_continuous: true
  obs_space: 3
  action_interval: 1
  action_max: 1
scenario: foil
hyperparameters:
  batch_size: 128
  buffer_capacity: 100000
  c_lr: 0.0003
  a_lr: 0.003
  alpha_lr: 0.0003
  alpha: 0.2
  epsilon: 0.5
  epsilon_end: 0.05
  gamma: 0.99
  hidden_size: 100
  num_hid_layer: 3
  target_replace: 30
  network: critic
  policy_type: gaussian
  clip_param: 0.2
  target_entropy_ratio: 0.7
  tau: 0.005
  tune_entropy: true
  marl: false
  learn_freq: 1
  learn_terminal: false
  theta: 10
  AD: 0.1875
  Phi: 20
  St: 0.08
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 50
  max_episodes: 300
  render: false
  save_interval: 100
time_weight: 50
y_weight: 0
alpha_weight: 50