algo: sac
envparameters:
  action_continuous: true
  action_space: 2
  n_player: 1
  obs_continuous: true
  obs_space: 6
scenario: foil
hyperparameters:
  batch_size: 128
  buffer_capacity: 10000
  c_lr: 0.001
  a_lr: 0.001
  alpha_lr: 0.001
  alpha: 0.2
  epsilon: 0.5
  epsilon_end: 0.05
  gamma: 0.99
  hidden_size: 128
  num_hid_layer: 3
  target_replace: 30
  network: critic
  policy_type: gaussian
  clip_param: 0.2
  target_entropy_ratio: 0.7
  tau: 0.001
  tune_entropy: true
  marl: false
  learn_freq: 1
  learn_terminal: false
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 50
  max_episodes: 300
  render: false
  save_interval: 100
time_weight: 50
y_weight: 0
alpha_weight: 50